name: Auto check task 1 submission

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run check script
        id: check
        run: |
          if [ ! -f "scripts/task1_flow.py" ]; then
            echo "檢查腳本未找到，請確保 repository 同步至最新版本" > check_output.txt
            echo "FAILED=true" >> $GITHUB_ENV
            exit 1
          else
            STUDENT_ID="${{ github.event.pull_request.title }}"
            echo "STUDENT_ID=$STUDENT_ID" >> GITHUB_ENV
            python scripts/task1_flow.py "$STUDENT_ID" > check_output.txt 2>&1
            EXIT_CODE=$?
            echo "PYTHON_EXIT_CODE=$EXIT_CODE"
            if [ $EXIT_CODE -ne 0 ]; then
              echo "FAILED=true" >> $GITHUB_ENV
              exit 1
            else
              echo "FAILED=false" >> $GITHUB_ENV
              exit 0
            fi
          fi

      - name: Auto Merge PR
        if: ${{ env.FAILED != 'true' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge

      - name: Comment on PR
        if: ${{ env.FAILED == 'true' }}
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const hasCommented = comments.data.some(comment => comment.body.includes('提交檢查未通過'));
            if (!hasCommented) {
              const output = require('fs').readFileSync('check_output.txt', 'utf8') || "無詳細錯誤訊息";
              const comment = `
                ## 提交檢查未通過
                \`\`\`
                ${output}
                \`\`\`
                請修正後重新提交 PR。
              `;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }