name: Check Task 1

on:
  pull_request:
    branches:
      - main

jobs:
  check_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run check script
        id: check
        run: |
          STUDENT_ID=$(basename ${{ github.event.pull_request.head.ref }})
          python scripts/task1_flow.py "$STUDENT_ID" > check_output.txt 2>&1 || echo "FAILED=true" >> $GITHUB_ENV
          cat check_output.txt  # 顯示檢查結果到日誌
          echo "CHECK_OUTPUT=$(cat check_output.txt)" >> $GITHUB_ENV

      - name: Auto Merge PR
        if: ${{ env.FAILED != 'true' }}  # 檢查通過時執行
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge

      - name: Comment and Close PR
        if: ${{ env.FAILED == 'true' }}  # 檢查失敗時執行
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `提交檢查未通過，以下是問題：\n\n${process.env.CHECK_OUTPUT}\n\n請修正後重新提交 PR。`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: 'closed'
            });
